### ISSUE TITLE
python3-vcstool python3-colcon-common-extensions python3-rosdep are from the ROS package repository

### ISSUE THREAD

**Issue by rjoomen** [tesseract-robotics/colcon-action#12]
If `ros-enabled` is false, `colcon-action@v7` fails because `python3-vcstool`, `python3-colcon-common-extensions`, and `python3-rosdep` cannot be found. See also https://github.com/tesseract-robotics/tesseract/pull/1006

**Comment by marip8** [comment]
Is the issue here that the name `ros-enabled` is a bit misleading? I would be okay with renaming it something like `add-ros-sources`

**Comment by rjoomen** [comment]
No, the issue is that `colcon-action` currently will fail when `ros-enabled` is set to false.

**Comment by marip8** [comment]
I guess we should just get rid of that option since `colcon` itself can't be installed now unless you add the ROS sources

**Comment by rjoomen** [comment]
Seems logical. It's the ROS build tool after all, not to mention rosdep, which even has ROS in the name :)

**Comment by rjoomen** [comment]
@Levi-Armstrong do you agree? We'll be requiring ROS for the CI of the intentionally ROS-agnostic Tesseract framework.

**Comment by marip8** [comment]
FWIW, it seems like adding the ROS sources is equivalent to adding a PPA. It doesn't force us to embed ROS into our code or force us to link against ROS; it just gives us the ability to use ROS infrastructure tools that happen to be convenient for building our projects whether they depend on ROS or not

**Comment by Levi-Armstrong** [comment]
If one of the option @johnwason proposed works I prefer that over adding the PPA.

**Comment by Levi-Armstrong** [comment]
Should be addressed by #14
